Default: &defaults
  database: PDiary.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: PDiary_test.sqlite3
  <<: *defaults

Staging:
  database: PDiary_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: PDiary_production.sqlite3
  poolsize: 100
  <<: *defaults
